reformat for modern nimble project structure and include picohttpparser as submodule
philip-wernersbach/nim-picohttpparser pull request #2
Opened 2023-04-13 01:57 UTC by termermc

This PR reformats the library into the new Nimble project structure, includes picohttpparser as a submodule (to avoid developers needing to manually include it), and moving `picohttpparser_api` module to `picohttpparser/api`.

2023-04-13 03:12 UTC, termermc commented
Hold on, I need to sort out how to get it working with the submodule

2023-04-13 04:06 UTC, termermc commented
Ok it's working properly now

2023-04-14 18:22 UTC, philip-wernersbach commented
Thank you for your work on this, and your contribution! I will review both PR's this weekend.

2023-04-16 00:35 UTC, philip-wernersbach requested changes
Some minor changes, looks good otherwise!

2023-04-16 00:35 UTC, philip-wernersbach commented on .gitmodules
> +	url = https://github.com/h2o/picohttpparser
There is already a `picohttpparser` submodule in `vendor/picohttpparser` (see lines 1-3). Can we continue to use that submodule instead of creating a new one?

If not, let's remove the old submodule and change the path of this one to `vendor-picohttpparser-c`. I prefer to have "vendor" in the path names of code that's included from another project, because that's the convention in other languages.

2023-04-16 00:35 UTC, philip-wernersbach commented on README.md
> +Install `picohttpparser` with Nimble and you're ready to go.
Does `nimble` check out the submodule properly?

2023-04-16 00:35 UTC, philip-wernersbach commented on picohttpparser.nim
> +export api
Do we need this file if people are using `import picohttpparser/api`? If not, let's delete this file.

2023-04-16 00:35 UTC, philip-wernersbach commented on picohttpparser/api.nim
> +{.compile: picoRoot & "/picohttpparser.c".}
Awesome!

2023-04-16 00:35 UTC, philip-wernersbach commented on picohttpparser/api.nim
>  converter toStringTableRef*(x: seq[phr_header]): StringTableRef =
Question: Do these two converter `proc`s still work? If not, don't worry about it. I'd just like to know if they work.

2023-04-16 00:42 UTC, termermc commented on picohttpparser/api.nim
>  converter toStringTableRef*(x: seq[phr_header]): StringTableRef =
If they're still used in the code then they work. So far I tested microasynchttpserver with the changes I made and it works right.

2023-04-16 00:43 UTC, termermc commented on README.md
> +Install `picohttpparser` with Nimble and you're ready to go.
Nimble handles it properly. I tested it with a new project and it did it fine.

2023-04-16 00:46 UTC, termermc commented on .gitmodules
> +	url = https://github.com/h2o/picohttpparser
I didn't even notice. I'll modify it to be in the vendor folder instead, my bad.

2023-04-16 01:00 UTC, termermc commented on .gitmodules
> +	url = https://github.com/h2o/picohttpparser
Done.

2023-04-16 01:01 UTC, termermc commented on picohttpparser.nim
> +export api
Nimble shows a warning if you don't have a file with the same name as your package at the package's source root. Best to keep the file around even though all it does it re-export APIs.

2023-04-16 05:29 UTC, philip-wernersbach approved these changes
Thank you! Merging and tagging.

2023-04-16 05:29 UTC, merged

2023-04-16 05:34 UTC, philip-wernersbach commented
Tagged as 0.11.0.